export const users = [
  {
    fullName: "Aarav Sharma",
    address: "123, MG Road, Delhi",
    tenthPassingYear: "2014",
    twelfthPassingYear: "2016",
    twelfthSpecialisation: "Science",
    diplomaSpecialisation: null,
    additionalSkills: "JavaScript, React",
    tenthCertificateUrl: "https://example.com/aarav/tenth-cert",
    twelfthCertificateUrl: "https://example.com/aarav/twelfth-cert",
    contactNumbers: "9876543210",
    aadhaarnumber: "123456789012",
    emailid: "aarav.sharma@example.com",
    picurl: "https://example.com/aarav/pic",
    aadhaarurl: "https://example.com/aarav/aadhaar",
    jobDetails: "Software Developer at ABC Corp",
  },
  {
    fullName: "Aditi Verma",
    address: "45, Sector 10, Mumbai",
    tenthPassingYear: "2013",
    twelfthPassingYear: "2015",
    twelfthSpecialisation: "Commerce",
    diplomaSpecialisation: null,
    additionalSkills: "Python, Data Analysis",
    tenthCertificateUrl: "https://example.com/aditi/tenth-cert",
    twelfthCertificateUrl: "https://example.com/aditi/twelfth-cert",
    contactNumbers: "9123456789",
    aadhaarnumber: "234567890123",
    emailid: "aditi.verma@example.com",
    picurl: "https://example.com/aditi/pic",
    aadhaarurl: "https://example.com/aditi/aadhaar",
    jobDetails: "Data Analyst at XYZ Ltd",
  },
  {
    fullName: "Rohan Patil",
    address: "22, JM Road, Pune",
    tenthPassingYear: "2012",
    twelfthPassingYear: "2014",
    twelfthSpecialisation: "Arts",
    diplomaSpecialisation: null,
    additionalSkills: "Graphic Design, Photoshop",
    tenthCertificateUrl: "https://example.com/rohan/tenth-cert",
    twelfthCertificateUrl: "https://example.com/rohan/twelfth-cert",
    contactNumbers: "9988776655",
    aadhaarnumber: "345678901234",
    emailid: "rohan.patil@example.com",
    picurl: "https://example.com/rohan/pic",
    aadhaarurl: "https://example.com/rohan/aadhaar",
    jobDetails: "Graphic Designer at Artify Studios",
  },
  {
    fullName: "Sakshi Gupta",
    address: "78, Park Avenue, Bengaluru",
    tenthPassingYear: "2015",
    twelfthPassingYear: null,
    twelfthSpecialisation: null,
    diplomaSpecialisation: "Computer Science",
    additionalSkills: "HTML, CSS, JavaScript",
    tenthCertificateUrl: "https://example.com/sakshi/tenth-cert",
    twelfthCertificateUrl: null,
    contactNumbers: "8765432109",
    aadhaarnumber: "456789012345",
    emailid: "sakshi.gupta@example.com",
    picurl: "https://example.com/sakshi/pic",
    aadhaarurl: "https://example.com/sakshi/aadhaar",
    jobDetails: "Front-end Developer at Dev Solutions",
  },
  {
    fullName: "Manish Yadav",
    address: "34, Link Road, Kolkata",
    tenthPassingYear: "2010",
    twelfthPassingYear: "2012",
    twelfthSpecialisation: "Science",
    diplomaSpecialisation: null,
    additionalSkills: "Networking, Cybersecurity",
    tenthCertificateUrl: "https://example.com/manish/tenth-cert",
    twelfthCertificateUrl: "https://example.com/manish/twelfth-cert",
    contactNumbers: "9988001122",
    aadhaarnumber: "567890123456",
    emailid: "manish.yadav@example.com",
    picurl: "https://example.com/manish/pic",
    aadhaarurl: "https://example.com/manish/aadhaar",
    jobDetails: "Network Engineer at NetSecure Inc",
  },
  {
    fullName: "Aarav Sharma",
    address: "123, MG Road, Delhi",
    tenthPassingYear: "2014",
    twelfthPassingYear: "2016",
    twelfthSpecialisation: "Science",
    diplomaSpecialisation: null,
    additionalSkills: "JavaScript, React",
    tenthCertificateUrl: "https://example.com/aarav/tenth-cert",
    twelfthCertificateUrl: "https://example.com/aarav/twelfth-cert",
    contactNumbers: "9876543210",
    aadhaarnumber: "123456789012",
    emailid: "aarav.sharma@example.com",
    picurl: "https://example.com/aarav/pic",
    aadhaarurl: "https://example.com/aarav/aadhaar",
    jobDetails: "Software Developer at ABC Corp",
  },
  {
    fullName: "Aditi Verma",
    address: "45, Sector 10, Mumbai",
    tenthPassingYear: "2013",
    twelfthPassingYear: "2015",
    twelfthSpecialisation: "Commerce",
    diplomaSpecialisation: null,
    additionalSkills: "Python, Data Analysis",
    tenthCertificateUrl: "https://example.com/aditi/tenth-cert",
    twelfthCertificateUrl: "https://example.com/aditi/twelfth-cert",
    contactNumbers: "9123456789",
    aadhaarnumber: "234567890123",
    emailid: "aditi.verma@example.com",
    picurl: "https://example.com/aditi/pic",
    aadhaarurl: "https://example.com/aditi/aadhaar",
    jobDetails: "Data Analyst at XYZ Ltd",
  },
  {
    fullName: "Rohan Patil",
    address: "22, JM Road, Pune",
    tenthPassingYear: "2012",
    twelfthPassingYear: "2014",
    twelfthSpecialisation: "Arts",
    diplomaSpecialisation: null,
    additionalSkills: "Graphic Design, Photoshop",
    tenthCertificateUrl: "https://example.com/rohan/tenth-cert",
    twelfthCertificateUrl: "https://example.com/rohan/twelfth-cert",
    contactNumbers: "9988776655",
    aadhaarnumber: "345678901234",
    emailid: "rohan.patil@example.com",
    picurl: "https://example.com/rohan/pic",
    aadhaarurl: "https://example.com/rohan/aadhaar",
    jobDetails: "Graphic Designer at Artify Studios",
  },
  {
    fullName: "Sakshi Gupta",
    address: "78, Park Avenue, Bengaluru",
    tenthPassingYear: "2015",
    twelfthPassingYear: null,
    twelfthSpecialisation: null,
    diplomaSpecialisation: "Computer Science",
    additionalSkills: "HTML, CSS, JavaScript",
    tenthCertificateUrl: "https://example.com/sakshi/tenth-cert",
    twelfthCertificateUrl: null,
    contactNumbers: "8765432109",
    aadhaarnumber: "456789012345",
    emailid: "sakshi.gupta@example.com",
    picurl: "https://example.com/sakshi/pic",
    aadhaarurl: "https://example.com/sakshi/aadhaar",
    jobDetails: "Front-end Developer at Dev Solutions",
  },
  {
    fullName: "Manish Yadav",
    address: "34, Link Road, Kolkata",
    tenthPassingYear: "2010",
    twelfthPassingYear: "2012",
    twelfthSpecialisation: "Science",
    diplomaSpecialisation: null,
    additionalSkills: "Networking, Cybersecurity",
    tenthCertificateUrl: "https://example.com/manish/tenth-cert",
    twelfthCertificateUrl: "https://example.com/manish/twelfth-cert",
    contactNumbers: "9988001122",
    aadhaarnumber: "567890123456",
    emailid: "manish.yadav@example.com",
    picurl: "https://example.com/manish/pic",
    aadhaarurl: "https://example.com/manish/aadhaar",
    jobDetails: "Network Engineer at NetSecure Inc",
  },
  {
    fullName: "User6 Name",
    address: "60, Random Street, Random City",
    tenthPassingYear: "2006",
    twelfthPassingYear: "2008",
    twelfthSpecialisation: "Science",
    diplomaSpecialisation: "Mechanical Engineering",
    additionalSkills: "Skill6, Skill7",
    tenthCertificateUrl: "https://example.com/user6/tenth-cert",
    twelfthCertificateUrl: "https://example.com/user6/twelfth-cert",
    contactNumbers: "912345676",
    aadhaarnumber: "678910111213",
    emailid: "user6@example.com",
    picurl: "https://example.com/user6/pic",
    aadhaarurl: "https://example.com/user6/aadhaar",
    jobDetails: "Software Developer",
  },
  {
    fullName: "User7 Name",
    address: "70, Random Street, Random City",
    tenthPassingYear: "2007",
    twelfthPassingYear: null,
    twelfthSpecialisation: null,
    diplomaSpecialisation: null,
    additionalSkills: "Skill7, Skill8",
    tenthCertificateUrl: "https://example.com/user7/tenth-cert",
    twelfthCertificateUrl: null,
    contactNumbers: "912345677",
    aadhaarnumber: "7891011121314",
    emailid: "user7@example.com",
    picurl: "https://example.com/user7/pic",
    aadhaarurl: "https://example.com/user7/aadhaar",
    jobDetails: "Mechanical Engineer",
  },
  {
    fullName: "User8 Name",
    address: "80, Random Street, Random City",
    tenthPassingYear: "2008",
    twelfthPassingYear: "20010",
    twelfthSpecialisation: "Science",
    diplomaSpecialisation: null,
    additionalSkills: "Skill8, Skill9",
    tenthCertificateUrl: "https://example.com/user8/tenth-cert",
    twelfthCertificateUrl: "https://example.com/user8/twelfth-cert",
    contactNumbers: "912345678",
    aadhaarnumber: "89101112131415",
    emailid: "user8@example.com",
    picurl: "https://example.com/user8/pic",
    aadhaarurl: "https://example.com/user8/aadhaar",
    jobDetails: "Software Developer",
  },
  {
    fullName: "User9 Name",
    address: "90, Random Street, Random City",
    tenthPassingYear: "2009",
    twelfthPassingYear: null,
    twelfthSpecialisation: null,
    diplomaSpecialisation: "Mechanical Engineering",
    additionalSkills: "Skill9, Skill10",
    tenthCertificateUrl: "https://example.com/user9/tenth-cert",
    twelfthCertificateUrl: null,
    contactNumbers: "912345679",
    aadhaarnumber: "910111213141516",
    emailid: "user9@example.com",
    picurl: "https://example.com/user9/pic",
    aadhaarurl: "https://example.com/user9/aadhaar",
    jobDetails: "Mechanical Engineer",
  },
  {
    fullName: "User10 Name",
    address: "100, Random Street, Random City",
    tenthPassingYear: "20010",
    twelfthPassingYear: "20012",
    twelfthSpecialisation: "Science",
    diplomaSpecialisation: null,
    additionalSkills: "Skill10, Skill11",
    tenthCertificateUrl: "https://example.com/user10/tenth-cert",
    twelfthCertificateUrl: "https://example.com/user10/twelfth-cert",
    contactNumbers: "9123456710",
    aadhaarnumber: "1011121314151617",
    emailid: "user10@example.com",
    picurl: "https://example.com/user10/pic",
    aadhaarurl: "https://example.com/user10/aadhaar",
    jobDetails: "Software Developer",
  },
  {
    fullName: "User11 Name",
    address: "110, Random Street, Random City",
    tenthPassingYear: "20011",
    twelfthPassingYear: null,
    twelfthSpecialisation: null,
    diplomaSpecialisation: null,
    additionalSkills: "Skill11, Skill12",
    tenthCertificateUrl: "https://example.com/user11/tenth-cert",
    twelfthCertificateUrl: null,
    contactNumbers: "9123456711",
    aadhaarnumber: "1112131415161718",
    emailid: "user11@example.com",
    picurl: "https://example.com/user11/pic",
    aadhaarurl: "https://example.com/user11/aadhaar",
    jobDetails: "Mechanical Engineer",
  },
  {
    fullName: "User12 Name",
    address: "120, Random Street, Random City",
    tenthPassingYear: "20012",
    twelfthPassingYear: "20014",
    twelfthSpecialisation: "Science",
    diplomaSpecialisation: "Mechanical Engineering",
    additionalSkills: "Skill12, Skill13",
    tenthCertificateUrl: "https://example.com/user12/tenth-cert",
    twelfthCertificateUrl: "https://example.com/user12/twelfth-cert",
    contactNumbers: "9123456712",
    aadhaarnumber: "1213141516171819",
    emailid: "user12@example.com",
    picurl: "https://example.com/user12/pic",
    aadhaarurl: "https://example.com/user12/aadhaar",
    jobDetails: "Software Developer",
  },
  {
    fullName: "User13 Name",
    address: "130, Random Street, Random City",
    tenthPassingYear: "20013",
    twelfthPassingYear: null,
    twelfthSpecialisation: null,
    diplomaSpecialisation: null,
    additionalSkills: "Skill13, Skill14",
    tenthCertificateUrl: "https://example.com/user13/tenth-cert",
    twelfthCertificateUrl: null,
    contactNumbers: "9123456713",
    aadhaarnumber: "1314151617181920",
    emailid: "user13@example.com",
    picurl: "https://example.com/user13/pic",
    aadhaarurl: "https://example.com/user13/aadhaar",
    jobDetails: "Mechanical Engineer",
  },
  {
    fullName: "User14 Name",
    address: "140, Random Street, Random City",
    tenthPassingYear: "20014",
    twelfthPassingYear: "20016",
    twelfthSpecialisation: "Science",
    diplomaSpecialisation: null,
    additionalSkills: "Skill14, Skill15",
    tenthCertificateUrl: "https://example.com/user14/tenth-cert",
    twelfthCertificateUrl: "https://example.com/user14/twelfth-cert",
    contactNumbers: "9123456714",
    aadhaarnumber: "1415161718192021",
    emailid: "user14@example.com",
    picurl: "https://example.com/user14/pic",
    aadhaarurl: "https://example.com/user14/aadhaar",
    jobDetails: "Software Developer",
  },
  {
    fullName: "User15 Name",
    address: "150, Random Street, Random City",
    tenthPassingYear: "20015",
    twelfthPassingYear: null,
    twelfthSpecialisation: null,
    diplomaSpecialisation: "Mechanical Engineering",
    additionalSkills: "Skill15, Skill16",
    tenthCertificateUrl: "https://example.com/user15/tenth-cert",
    twelfthCertificateUrl: null,
    contactNumbers: "9123456715",
    aadhaarnumber: "1516171819202122",
    emailid: "user15@example.com",
    picurl: "https://example.com/user15/pic",
    aadhaarurl: "https://example.com/user15/aadhaar",
    jobDetails: "Mechanical Engineer",
  },
  {
    fullName: "User16 Name",
    address: "160, Random Street, Random City",
    tenthPassingYear: "20016",
    twelfthPassingYear: "20018",
    twelfthSpecialisation: "Science",
    diplomaSpecialisation: null,
    additionalSkills: "Skill16, Skill17",
    tenthCertificateUrl: "https://example.com/user16/tenth-cert",
    twelfthCertificateUrl: "https://example.com/user16/twelfth-cert",
    contactNumbers: "9123456716",
    aadhaarnumber: "1617181920212223",
    emailid: "user16@example.com",
    picurl: "https://example.com/user16/pic",
    aadhaarurl: "https://example.com/user16/aadhaar",
    jobDetails: "Software Developer",
  },
  {
    fullName: "User17 Name",
    address: "170, Random Street, Random City",
    tenthPassingYear: "20017",
    twelfthPassingYear: null,
    twelfthSpecialisation: null,
    diplomaSpecialisation: null,
    additionalSkills: "Skill17, Skill18",
    tenthCertificateUrl: "https://example.com/user17/tenth-cert",
    twelfthCertificateUrl: null,
    contactNumbers: "9123456717",
    aadhaarnumber: "1718192021222324",
    emailid: "user17@example.com",
    picurl: "https://example.com/user17/pic",
    aadhaarurl: "https://example.com/user17/aadhaar",
    jobDetails: "Mechanical Engineer",
  },
  {
    fullName: "User18 Name",
    address: "180, Random Street, Random City",
    tenthPassingYear: "20018",
    twelfthPassingYear: "20020",
    twelfthSpecialisation: "Science",
    diplomaSpecialisation: "Mechanical Engineering",
    additionalSkills: "Skill18, Skill19",
    tenthCertificateUrl: "https://example.com/user18/tenth-cert",
    twelfthCertificateUrl: "https://example.com/user18/twelfth-cert",
    contactNumbers: "9123456718",
    aadhaarnumber: "1819202122232425",
    emailid: "user18@example.com",
    picurl: "https://example.com/user18/pic",
    aadhaarurl: "https://example.com/user18/aadhaar",
    jobDetails: "Software Developer",
  },
  {
    fullName: "User19 Name",
    address: "190, Random Street, Random City",
    tenthPassingYear: "20019",
    twelfthPassingYear: null,
    twelfthSpecialisation: null,
    diplomaSpecialisation: null,
    additionalSkills: "Skill19, Skill20",
    tenthCertificateUrl: "https://example.com/user19/tenth-cert",
    twelfthCertificateUrl: null,
    contactNumbers: "9123456719",
    aadhaarnumber: "1920212223242526",
    emailid: "user19@example.com",
    picurl: "https://example.com/user19/pic",
    aadhaarurl: "https://example.com/user19/aadhaar",
    jobDetails: "Mechanical Engineer",
  },
  {
    fullName: "User20 Name",
    address: "200, Random Street, Random City",
    tenthPassingYear: "20020",
    twelfthPassingYear: "20022",
    twelfthSpecialisation: "Science",
    diplomaSpecialisation: null,
    additionalSkills: "Skill20, Skill21",
    tenthCertificateUrl: "https://example.com/user20/tenth-cert",
    twelfthCertificateUrl: "https://example.com/user20/twelfth-cert",
    contactNumbers: "9123456720",
    aadhaarnumber: "2021222324252627",
    emailid: "user20@example.com",
    picurl: "https://example.com/user20/pic",
    aadhaarurl: "https://example.com/user20/aadhaar",
    jobDetails: "Software Developer",
  },
];

function findUsers(jobDetails) {
  return users.filter((user) => user.jobDetails.equals(jobDetails));
}